nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:4200'] # L'origine de ton app Angular
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600

    paths:
        '^/api/': # Remplace avec le préfixe de tes routes d'API
            allow_origin: ['http://localhost:4200']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
