<?php

namespace ContainerYyIZTBh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticlesControllereditService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.xqghpMM.App\Controller\ArticlesController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.xqghpMM'] ?? $container->load('get_ServiceLocator_XqghpMMService'));

        if (isset($container->privates['.service_locator.xqghpMM.App\\Controller\\ArticlesController::edit()'])) {
            return $container->privates['.service_locator.xqghpMM.App\\Controller\\ArticlesController::edit()'];
        }

        return $container->privates['.service_locator.xqghpMM.App\\Controller\\ArticlesController::edit()'] = $a->withContext('App\\Controller\\ArticlesController::edit()', $container);
    }
}
