<?php

namespace ContainerYyIZTBh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebug_Security_Authenticator_JsonLogin_ApiLoginService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'debug.security.authenticator.json_login.api_login' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/InteractiveAuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/EntryPoint/AuthenticationEntryPointInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/Debug/TraceableAuthenticator.php';

        $a = ($container->privates['debug.security.authenticator.json_login.api_login.inner'] ?? $container->load('getDebug_Security_Authenticator_JsonLogin_ApiLogin_InnerService'));

        if (isset($container->privates['debug.security.authenticator.json_login.api_login'])) {
            return $container->privates['debug.security.authenticator.json_login.api_login'];
        }

        return $container->privates['debug.security.authenticator.json_login.api_login'] = new \Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticator($a);
    }
}
