<?php

namespace ContainerYyIZTBh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebug_Security_Firewall_Authenticator_ApiLoginService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'debug.security.firewall.authenticator.api_login' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticatorManagerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/Debug/TraceableAuthenticatorManagerListener.php';

        $a = ($container->privates['debug.security.firewall.authenticator.api_login.inner'] ?? $container->load('getDebug_Security_Firewall_Authenticator_ApiLogin_InnerService'));

        if (isset($container->privates['debug.security.firewall.authenticator.api_login'])) {
            return $container->privates['debug.security.firewall.authenticator.api_login'];
        }

        return $container->privates['debug.security.firewall.authenticator.api_login'] = new \Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticatorManagerListener($a);
    }
}
