<?php

namespace ContainerSOYmO49;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9SvtZc1Service extends App_KernelProdDebugContainer
{
    /**
     * Gets the private '.service_locator.9SvtZc1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9SvtZc1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'event_dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'security.event_dispatcher.main' => ['privates', 'debug.security.event_dispatcher.main', 'getDebug_Security_EventDispatcher_MainService', false],
            'security.event_dispatcher.api_login' => ['privates', 'debug.security.event_dispatcher.api_login', 'getDebug_Security_EventDispatcher_ApiLoginService', true],
            'security.event_dispatcher.api_users_new' => ['privates', 'debug.security.event_dispatcher.api_users_new', 'getDebug_Security_EventDispatcher_ApiUsersNewService', true],
        ], [
            'event_dispatcher' => '?',
            'security.event_dispatcher.main' => '?',
            'security.event_dispatcher.api_login' => '?',
            'security.event_dispatcher.api_users_new' => '?',
        ]);
    }
}
