<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSOYmO49\App_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSOYmO49/App_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerSOYmO49.legacy');

    return;
}

if (!\class_exists(App_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerSOYmO49\App_KernelProdDebugContainer::class, App_KernelProdDebugContainer::class, false);
}

return new \ContainerSOYmO49\App_KernelProdDebugContainer([
    'container.build_hash' => 'SOYmO49',
    'container.build_id' => 'b8829ee9',
    'container.build_time' => 1740757555,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSOYmO49');
