<?php

namespace ContainerMS3z0ro;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D_S8QceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d.s8Qce' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d.s8Qce'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ArticlesController::index' => ['privates', '.service_locator.EtQatbL.App\\Controller\\ArticlesController::index()', 'getArticlesControllerindexService', true],
            'App\\Controller\\ArticlesController::new' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ArticlesController::new()', 'getArticlesControllernewService', true],
            'App\\Controller\\ArticlesController::page' => ['privates', '.service_locator.uOjHxUd.App\\Controller\\ArticlesController::page()', 'getArticlesControllerpageService', true],
            'App\\Controller\\ArticlesController::edit' => ['privates', '.service_locator.xqghpMM.App\\Controller\\ArticlesController::edit()', 'getArticlesControllereditService', true],
            'App\\Controller\\ArticlesController::delete' => ['privates', '.service_locator.xqghpMM.App\\Controller\\ArticlesController::delete()', 'getArticlesControllerdeleteService', true],
            'App\\Controller\\CommentaireController::createEditDelete' => ['privates', '.service_locator.Cj2p88g.App\\Controller\\CommentaireController::createEditDelete()', 'getCommentaireControllercreateEditDeleteService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.MbWBn3P.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\RegisterController::register' => ['privates', '.service_locator.5SuUxla.App\\Controller\\RegisterController::register()', 'getRegisterControllerregisterService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.PtEirWk.App\\Controller\\ResetPasswordController::request()', 'getResetPasswordControllerrequestService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.qHpfPrp.App\\Controller\\ResetPasswordController::reset()', 'getResetPasswordControllerresetService', true],
            'App\\Controller\\SearchController::handleSearch' => ['privates', '.service_locator._K5MRDO.App\\Controller\\SearchController::handleSearch()', 'getSearchControllerhandleSearchService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\UserController::new()', 'getUserControllernewService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.CQIMZqF.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.CQIMZqF.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ArticlesController:index' => ['privates', '.service_locator.EtQatbL.App\\Controller\\ArticlesController::index()', 'getArticlesControllerindexService', true],
            'App\\Controller\\ArticlesController:new' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ArticlesController::new()', 'getArticlesControllernewService', true],
            'App\\Controller\\ArticlesController:page' => ['privates', '.service_locator.uOjHxUd.App\\Controller\\ArticlesController::page()', 'getArticlesControllerpageService', true],
            'App\\Controller\\ArticlesController:edit' => ['privates', '.service_locator.xqghpMM.App\\Controller\\ArticlesController::edit()', 'getArticlesControllereditService', true],
            'App\\Controller\\ArticlesController:delete' => ['privates', '.service_locator.xqghpMM.App\\Controller\\ArticlesController::delete()', 'getArticlesControllerdeleteService', true],
            'App\\Controller\\CommentaireController:createEditDelete' => ['privates', '.service_locator.Cj2p88g.App\\Controller\\CommentaireController::createEditDelete()', 'getCommentaireControllercreateEditDeleteService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.MbWBn3P.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\RegisterController:register' => ['privates', '.service_locator.5SuUxla.App\\Controller\\RegisterController::register()', 'getRegisterControllerregisterService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.PtEirWk.App\\Controller\\ResetPasswordController::request()', 'getResetPasswordControllerrequestService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.qHpfPrp.App\\Controller\\ResetPasswordController::reset()', 'getResetPasswordControllerresetService', true],
            'App\\Controller\\SearchController:handleSearch' => ['privates', '.service_locator._K5MRDO.App\\Controller\\SearchController::handleSearch()', 'getSearchControllerhandleSearchService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\UserController::new()', 'getUserControllernewService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.CQIMZqF.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.CQIMZqF.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ArticlesController::index' => '?',
            'App\\Controller\\ArticlesController::new' => '?',
            'App\\Controller\\ArticlesController::page' => '?',
            'App\\Controller\\ArticlesController::edit' => '?',
            'App\\Controller\\ArticlesController::delete' => '?',
            'App\\Controller\\CommentaireController::createEditDelete' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\RegisterController::register' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SearchController::handleSearch' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ArticlesController:index' => '?',
            'App\\Controller\\ArticlesController:new' => '?',
            'App\\Controller\\ArticlesController:page' => '?',
            'App\\Controller\\ArticlesController:edit' => '?',
            'App\\Controller\\ArticlesController:delete' => '?',
            'App\\Controller\\CommentaireController:createEditDelete' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\RegisterController:register' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SearchController:handleSearch' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:delete' => '?',
        ]);
    }
}
