<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYyIZTBh\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYyIZTBh/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerYyIZTBh.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerYyIZTBh\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerYyIZTBh\App_KernelTestDebugContainer([
    'container.build_hash' => 'YyIZTBh',
    'container.build_id' => 'b997fb14',
    'container.build_time' => 1739792429,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYyIZTBh');
