<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCCG2F6I\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCCG2F6I/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCCG2F6I.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCCG2F6I\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCCG2F6I\App_KernelDevDebugContainer([
    'container.build_hash' => 'CCG2F6I',
    'container.build_id' => '9929243b',
    'container.build_time' => 1740062160,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCCG2F6I');
