<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3FSM8sb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3FSM8sb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3FSM8sb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3FSM8sb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3FSM8sb\App_KernelDevDebugContainer([
    'container.build_hash' => '3FSM8sb',
    'container.build_id' => '8956f556',
    'container.build_time' => 1740758082,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container3FSM8sb');
